# Generated by Django 4.2.3 on 2023-08-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('FRVR', '0004_alter_answer_question_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(default='FRVR/static/images/banner.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='FRVR/static/images/profile_picture.png', upload_to=''),
        ),
    ]
